### ISSUE TITLE
weird prompt

### ISSUE THREAD

**Issue by obaskly** [awekrx/ChatGPT-MidJourney-prompt#6]
I used the following code:

`
from chatGPTMidJourneyPrompt.mjPrompt import PromptGenerator

# supported authorization methods: via email and password, via token, via api key
config = {
  "email": "your_email",
  "password": "your_password",
  # or
  "session_token": "your_session_token",
  # or
  "api_key": "api_here",
}

promptGenerator = PromptGenerator(config)

prompt = promptGenerator.V5("human hunting a dog")

print(prompt)
`

I got this response : 
`human::10, hunting::10, dog::10, weapon::8, forest::7, trees::6, fear::5, chase::4, danger::4, wild::4, action::4, adrenaline::4, survival::4, predator::4, prey::4, nature::3, animal::3, escape::3, attack::3, wilderness::3, aggressive::3, intense::3, pursuit::3, fear::3, courage::2, violence::2, harm::2, harmlessness::2, fearlessness::2, defenselessness::2, defense::2, brutality::2, cruelty::2, dominance::2, submission::2 --v 5 --s 1000 --q 2`

Is this a normal prompt?

**Comment by awekrx** [comment]
This is normal because you have used the default method. It generates a phrase of 35 words. From which ChatGPT takes the basic words. He considered that all these words were necessary. You can reduce the number of words to make the prompt smaller.
  ```python
   prompt = promptGenerator.V5(text="human hunting a dog", words=5)
```
